{{- if .Values.global.monitoring.nodeMetrics.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: telegraf-node-conf
  labels:
{{ include "common.labels" . | indent 4 }}
data:
  telegraf.conf: |
    [global_tags]
      role = "k8s-node"

    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      debug = false
      logtarget = "stderr"
      hostname = "$HOSTNAME"
      omit_hostname = false

    [[outputs.influxdb]]
      urls = ["http://influxdb.{{ .Release.Namespace }}:8086/"]
      database = "telegraf"
      retention_policy = "autogen"
      write_consistency = "any"
      timeout = "5s"

    [[inputs.cpu]]
      percpu = false
      totalcpu = true
      collect_cpu_time = false
      report_active = false

    [[inputs.mem]]

    [[inputs.disk]]
      mount_points = ["/host/rootfs"]
      ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

    [[inputs.swap]]

    [[inputs.system]]
{{- end }}
