apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: grafana
{{ include "common.labels" . | indent 4 }}
  name: grafana
  namespace: {{ .Release.Namespace | quote }}
spec:
  serviceName: grafana
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
      annotations:
        {{- if .Values.global.podAnnotations }}
        {{ toYaml .Values.global.podAnnotations | default "" | nindent 8 }}
        {{- end }}
        {{- if .Values.grafana.podAnnotations }}
        {{ toYaml .Values.grafana.podAnnotations | default "" | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.affinity }}
      affinity:
        {{ toYaml .Values.affinity | default "" | nindent 8 }}
      {{- end }}
      securityContext:
          runAsUser: 472
          fsGroup: 472
      containers:
        - image: {{ .Values.grafana.image }}
          name: grafana
          ports:
            - containerPort: 3000
          readinessProbe:
            failureThreshold: 3
            httpGet:
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-claim
            - mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
              name: grafana-provisioning
              subPath: datasource.yaml
            - mountPath: /etc/grafana/provisioning/dashboards/default.yaml
              name: grafana-provisioning
              subPath: default-dashboard.yaml
            - mountPath: /var/lib/grafana/dashboards/jambonz-dashboard.json
              name: grafana-provisioning
              subPath: jambonz-dashboard.json
            - mountPath: /var/lib/grafana/dashboards/jambonz-heplify.json
              name: grafana-provisioning
              subPath: jambonz-heplify.json
            {{- if .Values.global.monitoring.nodeMetrics.enabled }}
            - mountPath: /var/lib/grafana/dashboards/k8s-nodes.json
              name: grafana-provisioning
              subPath: k8s-nodes.json
            {{- end }}
            {{- if .Values.global.logging.enabled }}
            - mountPath: /var/lib/grafana/dashboards/logs/logs-feature-server.json
              name: grafana-provisioning
              subPath: logs-feature-server.json
            - mountPath: /var/lib/grafana/dashboards/logs/logs-sbc-sip.json
              name: grafana-provisioning
              subPath: logs-sbc-sip.json
            - mountPath: /var/lib/grafana/dashboards/logs/logs-sbc-inbound.json
              name: grafana-provisioning
              subPath: logs-sbc-inbound.json
            - mountPath: /var/lib/grafana/dashboards/logs/logs-sbc-outbound.json
              name: grafana-provisioning
              subPath: logs-sbc-outbound.json
            - mountPath: /var/lib/grafana/dashboards/logs/logs-api-server.json
              name: grafana-provisioning
              subPath: logs-api-server.json
            {{- end }}
      restartPolicy: Always
      volumes:
      - name: grafana-provisioning
        configMap:
          name: grafana-provisioning
          items:
          - key: datasource.yaml
            path: datasource.yaml
          - key: default-dashboard.yaml
            path: default-dashboard.yaml
          - key: jambonz-dashboard.json
            path: jambonz-dashboard.json
          - key: jambonz-heplify.json
            path: jambonz-heplify.json
          {{- if .Values.global.monitoring.nodeMetrics.enabled }}
          - key: k8s-nodes.json
            path: k8s-nodes.json
          {{- end }}
          {{- if .Values.global.logging.enabled }}
          - key: logs-feature-server.json
            path: logs-feature-server.json
          - key: logs-sbc-sip.json
            path: logs-sbc-sip.json
          - key: logs-sbc-inbound.json
            path: logs-sbc-inbound.json
          - key: logs-sbc-outbound.json
            path: logs-sbc-outbound.json
          - key: logs-api-server.json
            path: logs-api-server.json
          {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: grafana-claim
    spec:
      accessModes: ["ReadWriteOnce"]
      {{- if .Values.storageClassName }}
      storageClassName: {{ .Values.storageClassName }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.grafana.storage }}
