apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "common.labels" . | indent 4 }}
  annotations:
{{- if .Values.global.traefik.tls.enabled }}
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    cert-manager.io/cluster-issuer: {{ .Values.global.traefik.tls.clusterIssuer }}
{{- else }}
    traefik.ingress.kubernetes.io/router.entrypoints: web
{{- end }}
spec:
  ingressClassName: traefik
  rules:
    - host: {{ required "hostname for the grafana portal" .Values.grafana.hostname }}
      http:
        paths:
        - backend:
            service:
              name: grafana
              port: 
                number: 3000
          path: /
          pathType: Prefix
{{- if .Values.global.traefik.tls.enabled }}
  tls:
  - hosts:
    - {{ required "hostname for the grafana" .Values.grafana.hostname }}
    secretName: jambonz-grafana-tls
{{- end }}
