apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "common.labels" . | indent 4 }}
  annotations:
{{- if .Values.global.traefik.tls.enabled }}
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    cert-manager.io/cluster-issuer: {{ .Values.global.traefik.tls.clusterIssuer }}
{{- else }}
    traefik.ingress.kubernetes.io/router.entrypoints: web
{{- end }}
spec:
  ingressClassName: traefik
  rules:
    - host: {{ include "jambonz.webappHostname" . }}
      http:
        paths:
        - backend:
            service:
              name: webapp
              port: 
                number: 3001
          path: /
          pathType: Prefix
{{- if .Values.global.traefik.tls.enabled }}
  tls:
  - hosts:
    - {{ include "jambonz.webappHostname" . }}
    secretName: jambonz-webapp-tls
{{- end }}
